### ISSUE TITLE
Figure out the approach to take for sending/receiving texts (using iMessage/Gmail/Twilio?)

### ISSUE THREAD

**Issue by eveningsamurai** [themoose3/Recreo#10]

**Comment by anjlal** [comment]
https://www.twilio.com/blog/2016/11/how-to-send-an-sms-from-ios-in-swift.html

**Comment by eveningsamurai** [comment]
Looks like there is something called the MessageUI framework within iOS as well to send out emails/messages.(Older) Examples below

- https://www.appcoda.com/ios-programming-create-email-attachment/
- https://www.appcoda.com/ios-programming-send-sms-text-message/

But this seems to happen with in the context of say an iMessage or the email app. So not sure if this fits into our goal of showing the consolidated list of messages to the user, but maybe something to look at.

**Comment by anjlal** [comment]
Thanks, Avinash -- I saw Message UI, as well when researching. I pinged Tim to get his opinion on which one makes the most sense to use.

**Comment by anjlal** [comment]
This is what Tim came back with, "I would use Twilio; it's a more flexible solution and in practice you want to choose things that will support your iOS and android app." This resonates with our earlier conversations.

**Comment by anjlal** [comment]
Got this to work with my Twilio test credentials. Going to close for now.
