### ISSUE TITLE
Design your database schema in Parse

### ISSUE THREAD

**Issue by eveningsamurai** [themoose3/Recreo#3]
*Blocked by*
Parse understanding issue

*Context*

*Deliverable*
Designing the schema in Parse

**Comment by anjlal** [comment]
I can get started on designing a basic schema. Did we decide whether to stick with Parse or try Firebase?

**Comment by anjlal** [comment]
Invite schema:

- Invite ID
- Invitor 
- Invitee(s)
- Invitees contact info (phone number/email address)
- Date 
- Time
- Address of location

**Comment by eveningsamurai** [comment]
I have just asked Tim this question, I am going through Firebase now. Hopefully should have an opinion in a few hours. In my very brief experience with the Parse server on Heroku, trying to post/pull an image for a demo was slow. Not sure if it will be any better with Firebase, but we can try.
Firebase does seem to be more popular now because its a managed solution(by Google) v.s. Parse server which we have to manage ourselves (earlier managed by Facebook but not managing it anymore)

**Comment by anjlal** [comment]
For posterity, Avinash and Angie completed this during working session on 4/30.

**Comment by eveningsamurai** [comment]
Attached is the schema representation
![groupproject_schema](https://cloud.githubusercontent.com/assets/2394082/25574333/4a91655a-2e02-11e7-88ae-95436f991b3b.jpg)
