### ISSUE TITLE
Figure out an approach to get contacts from contact list

### ISSUE THREAD

**Issue by eveningsamurai** [themoose3/Recreo#6]
*Blocked by*

*Deliverables*
* Get contacts from the phone contact list

**Comment by devretravl** [comment]
I will research about this issue. Don't know how to assign this to me.

**Comment by SideokCalebYou** [comment]
Sorry guys, that is my different id. I will let you know after researching it! thanks!

**Comment by SideokCalebYou** [comment]
Research completed and implemented in our project.
