### ISSUE TITLE
Create view controllers needed for early functionality

### ISSUE THREAD

**Issue by eveningsamurai** [themoose3/Recreo#9]
*Login Screen*
* Login / Signup ViewController can login with email address/pw or via FB OAuth.
* ResetPasswordViewController (nice-to-have)

*Event Feed*
* EventViewController lists out current events, and has hamburger menu and link to create new event in nav bar. There should be a search bar, as well.

*Event Detail*
* EventDetailViewController displays event details (e.g. event name, date/time, location, description) , and link to photo gallery.

*Chat Conversation*
* Shows chat conversation.

*Hamburger Menu*
* Profile and Archives are the two choices for now. Settings is a nice-to-have.

*Archives*
* List of events that have expired

*Profile*
* ProfileViewController should allow user to update profile photo (can select from photo library or take photo with camera), and edit name, email, and phone number.

*Create Event*
* AddEventViewController is a form where you can specify event's name, venue, date/time, description, and invitees. It should send a SMS to all invitees.

*Contact List*
* ContactViewController displays list of contacts from contact list. Selected invitees will be sent back to AddEventViewController.

*Gallery*
* GalleryViewController should display images and have ability to upload / delete photos.

**Comment by anjlal** [comment]
How should we split this up? We could each take 2-3 view controllers.

**Comment by eveningsamurai** [comment]
Yeah sure, I can take the Login screen controllers

**Comment by anjlal** [comment]
As of 4/30, LoginVC(AP), EventVC (AP), AddEvent(AP), EventDetailVC(AL), ProfileVC(AL), GalleryVC(AL), and ContactVC(SY).

**Comment by eveningsamurai** [comment]
Attaching the discussed list of controllers
![groupproject_controllers](https://cloud.githubusercontent.com/assets/2394082/25574398/dccdcd64-2e02-11e7-8191-66c88970db34.jpg)

**Comment by eveningsamurai** [comment]
Marking as complete
